//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoTrend_Industry_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int emailID { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public byte[] attachment { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateSent { get; set; }
        public Nullable<bool> approved { get; set; }
        public Nullable<bool> lockedOut { get; set; }
        public Nullable<int> supplierID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
