//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoTrend_Industry_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int logID { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> logDate { get; set; }
        public string body { get; set; }
        public Nullable<int> salesRepID { get; set; }
        public string salesRepName { get; set; }
        public Nullable<int> contactID { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
