//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoTrend_Industry_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesRep()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public int salesRepID { get; set; }
        public string email { get; set; }
        public string branch { get; set; }
        public string name { get; set; }
        public Nullable<int> contactID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
